Adding video block example to about us page
vtex-apps/store-theme pull request #235
Opened 2020-11-16 17:01 UTC by icazevedo

#### What problem is this solving?

This PR adds an example of video block usage to the about us page.

#### How to test it?

It's the second slide on the [about us](https://icarovideoblock--storecomponents.myvtex.com/about-us) page.

#### Screenshots or example usage:

<img width="780" alt="Screen Shot 2020-11-16 at 1 59 15 PM" src="https://user-images.githubusercontent.com/8127610/99283548-ec5dec00-2813-11eb-84f2-3a3f4071d67d.png">

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/iHOwdoVuWD4Bi/giphy.gif)

2020-11-16 17:31 UTC, victorhmp requested changes

2020-11-16 17:31 UTC, victorhmp commented on CHANGELOG.md
> +Example of [vtex.store-video](https://github.com/vtex-apps/store-video) usage.
```suggestion
- Example of [vtex.store-video](https://github.com/vtex-apps/store-video) usage.
```

2020-11-16 18:46 UTC, victorhmp approved these changes

2020-11-17 13:39 UTC, klzns approved these changes
I would move the video block bellow the current content instead of putting in a slider layout. I think it's a more common use-case.

2020-11-17 20:50 UTC, victorhmp approved these changes

2020-11-19 13:33 UTC, klzns approved these changes

2020-11-24 12:04 UTC, vitorflg approved these changes

2020-11-30 18:34 UTC, merged