Adding example of multiple search gallery layouts usage
vtex-apps/store-theme pull request #240
Opened 2021-01-06 23:25 UTC by icazevedo

#### What problem is this solving?

This PR adds the new gallery layout component to the store. It adds the list layout and allows the user to choose between them. It has different product-summaries for each layout and they vary by device (mobile/desktop/`1300px+`) in quantity and type.

#### How to test it?

[Workspace](https://icarosearch--storecomponents.myvtex.com/apparel---accessories)

#### Screenshots or example usage:

<img width="366" alt="Screen Shot 2021-01-06 at 20 18 53" src="https://user-images.githubusercontent.com/8127610/103832157-68c6bb80-505c-11eb-8d56-1feedfda32c7.png">

<img width="587" alt="Screen Shot 2021-01-06 at 20 19 19" src="https://user-images.githubusercontent.com/8127610/103832197-7a0fc800-505c-11eb-9eb3-7f7e2057a674.png">

#### Related to / Depends on

Depends on [search-result#473](https://github.com/vtex-apps/search-result/pull/473)
Depends on [responsive-values#11](https://github.com/vtex-apps/responsive-values/pull/11)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/jd6TVgsph6w7e/source.gif)

2021-01-06 23:57 UTC, klzns approved these changes
![](https://media.giphy.com/media/iJP6mBmZyqKYTBmrav/giphy.gif)

2021-01-06 23:59 UTC, klzns requested changes

2021-01-06 23:59 UTC, klzns commented on store/blocks/pdp/product-specifications.jsonc
> +  "product-specification-group#summary": {
Ops, the blocks of this folder should only be related to pdp

2021-01-06 23:59 UTC, klzns commented on styles/css/vtex.flex-layout.css
> +.flexRow--orderByAndSwitcher {
Put this in a folder like `styles/css/search/vtex.flex-layout.css`

2021-01-06 23:59 UTC, klzns commented on styles/css/vtex.product-summary.css
> +.nameContainer--summaryListDesktop {
You can also move this changes to the new folder

2021-01-06 23:59 UTC, klzns commented on styles/css/vtex.rich-text.css
> +.paragraph--summarySpecificationBullet {
same

2021-01-06 23:59 UTC, klzns commented on styles/css/vtex.store-components.css
> +.productBrandName--summaryListDesktop {
same

2021-01-07 20:00 UTC, klzns approved these changes

2021-01-12 16:19 UTC, igorbrasileiro approved these changes
LGTM. Left one comment

2021-01-12 16:19 UTC, igorbrasileiro commented on store/blocks/product-summary/product-summary-list.jsonc
> +      "text": "BUY NOW", //internacionalizar
This should be internationalized?!

2021-01-12 20:54 UTC, victorhmp commented on store/blocks/product-summary/product-summary-list.jsonc
> +      "text": "BUY NOW", //internacionalizar
Yep, it could be! Using the Site Editor

2021-01-12 20:54 UTC, victorhmp approved these changes

2021-01-14 12:32 UTC, icazevedo commented on store/blocks/product-summary/product-summary-list.jsonc
> +      "text": "BUY NOW", //internacionalizar
I ended up forgetting to remove it 😅

2021-01-14 12:35 UTC, merged