Performance optimization changes by VTEX Growth Hacking team
vtex-apps/store-theme pull request #251
Opened 2022-05-25 08:15 UTC by brunovaletta

#### What problem is this solving?

Changes on the theme layout and blocks' properties to improve performance measured by Google Lighthouse. 

Previous performance score:
![image](https://user-images.githubusercontent.com/59453854/170212375-af0288ad-91f5-4d59-a32b-d8ca0e012bb4.png)

Score after changes:
![image](https://user-images.githubusercontent.com/59453854/170213357-6967eda4-3749-42cf-a61a-ca6acdbff088.png)

#### How to test it?

A copy of this theme is installed here:
https://storetheme.vtex.com/?workspace=vtexprojectnewstoretheme

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media2.giphy.com/media/pCWxDWgxkOiepk55T8/giphy.gif?cid=ecf05e47sxq6z7x06ze3oqydt3aa9yia1060mpoc9gwatf9y&rid=giphy.gif&ct=g)

2022-05-25 13:01 UTC, mateussaggin approved these changes

2022-05-25 20:08 UTC, victorhmp requested changes
Just some minor suggestions ;)

Oh! And notice that a new major was released earlier today, so please rebase this branch with master, no conflicts should happen (after you undo the changes in `manifest.json`).

Some awesome results here!! Thanks so much 😄

2022-05-25 20:08 UTC, victorhmp commented on CHANGELOG.md
> +- Fixed height in `list-context.image-list#demo` example
This is a nitpick, but could you add `.`s to all entries? 😂

2022-05-25 20:08 UTC, victorhmp commented on CHANGELOG.md
> +- Removed `notification.bar#home` from header
```suggestion
- `notification.bar#home` from header
```

2022-05-30 13:13 UTC, victorhmp requested changes

2022-06-02 20:45 UTC, victorhmp requested changes

2022-06-02 20:45 UTC, victorhmp commented on styles/css/vtex.flex-layout.css
> +    }
```suggestion
    padding: 0 1rem;
  }
```

2022-06-02 20:45 UTC, victorhmp commented on styles/css/vtex.store-components.css
> +    }
```suggestion
    padding: 140px;
  }
```

2022-06-02 20:45 UTC, victorhmp commented on styles/css/vtex.store-components.css
> +    }
```suggestion
     font-size: 40px;
  }
```

2022-06-02 20:45 UTC, victorhmp commented on styles/css/vtex.store-components.css
> +    }
```suggestion
    width: 30%;
  }
```

2022-06-02 20:45 UTC, victorhmp commented on styles/css/vtex.store-components.css
> +    }
```suggestion
    margin-bottom: 0px;
    max-height: 600px;
  }
```

2022-06-07 18:59 UTC, merged